### PR TITLE
fix: wrong devicemotion handling on iPad

### LINKED ISSUE #326: iPad Pro 11" or iPad 9.7" IOS v13.6.1 panorama shakes when gyro enabled
I've been testing a number of your online panoviewer demos and everything is working well on Chrome/IE 11 on the PC. Also working fine on an iPhone Xs running IOS v13.6.1, but when I tested on two iPad's I own, with any of the demo panorama examples and the gyro enabled the image is shaking badly making it unusable, moving the phone is causing the panorama to move, but it shakes so badly I can't tap on any hotspot.

If I don't enable the gyro (i.e. select 'deny' when prompted to enable gryo) then the 360 panorama works correctly when I scroll around the screen.

Let me know if you need any more info, hopefully it's a simple fix.  Thanks Rob

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#326

## Details
This fixes #326

### CODE REVIEW

File: src/YawPitchControl/input/FusionPoseSensor.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import {quat} from "gl-matrix";
 import PosePredictor from "webvr-polyfill/src/sensor-fusion/pose-predictor";
 import MathUtil from "webvr-polyfill/src/math-util";
 import Util from "webvr-polyfill/src/util";
-import {window} from "../../utils/browser";
+import {window, IS_IOS, IS_SAFARI_ON_DESKTOP} from "../../utils/browser";
```
Comment (mixed) [inline src/YawPitchControl/input/FusionPoseSensor.js:6]: Are there any issues where you can't use an `eg.agent`?

File: src/YawPitchControl/input/FusionPoseSensor.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ export default class FusionPoseSensor extends Component {
 		this.filterToWorldQ = new MathUtil.Quaternion();
 
 		this.isFirefoxAndroid = Util.isFirefoxAndroid();
-		this.isIOS = Util.isIOS();
+		this.isIOS = IS_IOS || IS_SAFARI_ON_DESKTOP;
```
Comment (daybrush) [inline src/YawPitchControl/input/FusionPoseSensor.js:32]: Can mac safari be included in iOS?

**Review by daybrush — APPROVED** [review]
LGTM
